import React, { useState } from 'react';
import { 
  BookOpen, 
  UploadCloud, 
  MessageSquare, 
  Share2, 
  Database, 
  ShieldCheck, 
  Brain, 
  HelpCircle, 
  ChevronDown, 
  ChevronUp, 
  ArrowRight,
  FileText
} from 'lucide-react';

export default function GuidePage({ setActiveTab }) {
  const [openFaq, setOpenFaq] = useState(null);

  const steps = [
    {
      num: '01',
      title: 'Upload Documents',
      icon: UploadCloud,
      color: '#2563EB',
      bg: '#EFF6FF',
      desc: 'Upload PDF, DOCX, TXT, or MD documents. Automatically parse document layouts, tables, and raw text formatting.',
      actionTab: 'upload',
      actionText: 'Upload Documents'
    },
    {
      num: '02',
      title: 'Multi-Entity Extraction',
      icon: Brain,
      color: '#8B5CF6',
      bg: '#F5F3FF',
      desc: 'The LLM intelligence extraction engine automatically discovers entities (Concepts, Technologies, Organizations, People) and relationship triples.'
    },
    {
      num: '03',
      title: 'Knowledge Base & Graph',
      icon: Share2,
      color: '#0EA5E9',
      bg: '#F0F9FF',
      desc: 'Structured Markdown Wiki articles are automatically generated and indexed alongside an interactive Knowledge Graph visualization.',
      actionTab: 'wiki',
      actionText: 'Explore Knowledge'
    },
    {
      num: '04',
      title: 'Grounded QA Chat',
      icon: MessageSquare,
      color: '#10B981',
      bg: '#ECFDF5',
      desc: 'Ask complex questions to the grounded Chatbot. Answers are generated with zero hallucination and include click-through citations to source wiki pages.',
      actionTab: 'chat',
      actionText: 'Start AI Chat'
    }
  ];

  const faqs = [
    {
      q: 'What document formats are supported?',
      a: 'WikiMind supports PDF, DOCX, TXT, Markdown (.md), Excel (.xlsx, .xls), CSV, PPTX, HTML, and Image OCR formats.'
    },
    {
      q: 'How does cloud storage & persistence work?',
      a: 'All generated wiki articles, knowledge graph node relationships, chat sessions, and message history are automatically saved and synced.'
    },
    {
      q: 'What is Grounded QA with zero hallucination?',
      a: 'When you ask a question in Chat, WikiMind searches your ingested document context vectors. If relevant knowledge is missing, the AI explicitly states it cannot find grounded proof instead of guessing.'
    },
    {
      q: 'How do I view source citations?',
      a: 'Every answer generated by the assistant displays clickable citation badges. Clicking any citation opens the exact Wiki Knowledge article in the Knowledge Base tab.'
    }
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '32px', width: '100%', maxWidth: '1000px', margin: '0 auto', paddingBottom: '40px' }}>
      
      {/* Hero Header */}
      <div style={{ textAlign: 'center', paddingTop: '10px' }}>
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          padding: '6px 14px',
          borderRadius: '9999px',
          backgroundColor: '#F1F5F9',
          border: '1px solid #E2E8F0',
          fontSize: '12.5px',
          fontWeight: '600',
          color: '#09090B',
          marginBottom: '16px'
        }}>
          <BookOpen size={14} color="#2563EB" />
          <span>Platform User Guide & Documentation</span>
        </div>

        <h1 style={{ fontSize: '36px', fontWeight: '800', color: '#09090B', letterSpacing: '-0.8px', marginBottom: '12px' }}>
          How <span style={{ color: '#2563EB' }}>WikiMind</span> Works
        </h1>
        <p style={{ fontSize: '15px', color: '#64748B', maxWidth: '640px', margin: '0 auto', lineHeight: '1.6' }}>
          Learn how to turn your raw documents into structured Wiki articles, traversable Knowledge Graphs, and grounded AI assistant conversations.
        </p>
      </div>

      {/* 4-Step Interactive Workflow Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))', gap: '20px', position: 'relative' }}>
        {steps.map((s, idx) => {
          const IconComp = s.icon;
          return (
            <div 
              key={idx}
              className="memora-card"
              style={{
                backgroundColor: '#FFFFFF',
                border: '1px solid #E2E8F0',
                borderRadius: '16px',
                padding: '24px 20px',
                display: 'flex',
                flexDirection: 'column',
                gap: '14px',
                position: 'relative'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div style={{
                  width: '40px',
                  height: '40px',
                  borderRadius: '10px',
                  backgroundColor: s.bg,
                  display: 'inline-flex',
                  alignItems: 'center',
                  justify: 'center',
                  flexShrink: 0
                }}>
                  <IconComp size={20} color={s.color} style={{ display: 'block', margin: 'auto' }} />
                </div>
                <span style={{ fontSize: '20px', fontWeight: '800', color: '#CBD5E1' }}>{s.num}</span>
              </div>

              <div style={{ flex: 1 }}>
                <h3 style={{ fontSize: '16px', fontWeight: '700', color: '#09090B', marginBottom: '6px' }}>{s.title}</h3>
                <p style={{ fontSize: '12.5px', color: '#64748B', lineHeight: '1.5' }}>{s.desc}</p>
              </div>

              {s.actionTab && (
                <button
                  onClick={() => setActiveTab(s.actionTab)}
                  style={{
                    marginTop: '8px',
                    padding: '8px 16px',
                    borderRadius: '9999px',
                    backgroundColor: s.color,
                    color: '#FFFFFF',
                    border: 'none',
                    fontSize: '12px',
                    fontWeight: '700',
                    cursor: 'pointer',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '6px',
                    alignSelf: 'flex-start',
                    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
                    transition: 'transform 0.15s ease'
                  }}
                >
                  <span>{s.actionText}</span>
                  <ArrowRight size={13} />
                </button>
              )}

              {/* Connecting Flow Arrow pointing to next step */}
              {idx < steps.length - 1 && (
                <div 
                  style={{
                    position: 'absolute',
                    right: '-18px',
                    top: '50%',
                    transform: 'translateY(-50%)',
                    zIndex: 3,
                    backgroundColor: '#FFFFFF',
                    border: '2px solid #2563EB',
                    width: '36px',
                    height: '36px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justify: 'center',
                    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.25)'
                  }}
                  title="Next Workflow Step"
                >
                  <ArrowRight size={18} color="#2563EB" />
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Feature Architecture Overview */}
      <div style={{
        backgroundColor: '#FFFFFF',
        border: '1px solid #E2E8F0',
        borderRadius: '20px',
        padding: '28px',
        boxShadow: '0 8px 30px rgba(0,0,0,0.03)'
      }}>
        <h2 style={{ fontSize: '20px', fontWeight: '700', color: '#09090B', marginBottom: '20px' }}>
          Core Architectural Highlights
        </h2>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px' }}>
          <div style={{ display: 'flex', gap: '14px' }}>
            <div style={{ width: '36px', height: '36px', borderRadius: '8px', backgroundColor: '#09090B', color: '#FFF', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <FileText size={18} />
            </div>
            <div>
              <h4 style={{ fontSize: '15px', fontWeight: '600', color: '#09090B', marginBottom: '4px' }}>LlamaParse Document Ingestion</h4>
              <p style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5' }}>Extracts text, headers, and structured tables accurately from complex PDFs and documents.</p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '14px' }}>
            <div style={{ width: '36px', height: '36px', borderRadius: '8px', backgroundColor: '#09090B', color: '#FFF', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <Share2 size={18} />
            </div>
            <div>
              <h4 style={{ fontSize: '15px', fontWeight: '600', color: '#09090B', marginBottom: '4px' }}>Interactive 2D Knowledge Graph</h4>
              <p style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5' }}>Canvas physics simulation engine allowing you to click, drag, zoom, and inspect topic connections.</p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '14px' }}>
            <div style={{ width: '36px', height: '36px', borderRadius: '8px', backgroundColor: '#09090B', color: '#FFF', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <Database size={18} />
            </div>
            <div>
              <h4 style={{ fontSize: '15px', fontWeight: '600', color: '#09090B', marginBottom: '4px' }}>Turso Edge Cloud Database</h4>
              <p style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5' }}>Cross-device persistent storage for chat sessions, message history, wiki pages, and graph edges.</p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '14px' }}>
            <div style={{ width: '36px', height: '36px', borderRadius: '8px', backgroundColor: '#09090B', color: '#FFF', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <ShieldCheck size={18} />
            </div>
            <div>
              <h4 style={{ fontSize: '15px', fontWeight: '600', color: '#09090B', marginBottom: '4px' }}>Grounded Q&A Verification</h4>
              <p style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5' }}>Zero-hallucination verification ensuring every answer is strictly backed by ingested source citations.</p>
            </div>
          </div>
        </div>
      </div>

      {/* FAQ Accordion */}
      <div style={{
        backgroundColor: '#FFFFFF',
        border: '1px solid #E2E8F0',
        borderRadius: '20px',
        padding: '28px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '20px' }}>
          <HelpCircle size={22} color="#09090B" />
          <h2 style={{ fontSize: '20px', fontWeight: '700', color: '#09090B' }}>Frequently Asked Questions</h2>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          {faqs.map((faq, fIdx) => {
            const isOpen = openFaq === fIdx;
            return (
              <div 
                key={fIdx}
                style={{
                  border: '1px solid #F1F5F9',
                  borderRadius: '12px',
                  backgroundColor: isOpen ? '#F8FAFC' : '#FFFFFF',
                  overflow: 'hidden',
                  transition: 'all 0.2s ease'
                }}
              >
                <button
                  onClick={() => setOpenFaq(isOpen ? null : fIdx)}
                  style={{
                    width: '100%',
                    padding: '14px 18px',
                    display: 'flex',
                    alignItems: 'center',
                    justify: 'space-between',
                    backgroundColor: 'transparent',
                    border: 'none',
                    textAlign: 'left',
                    fontSize: '14.5px',
                    fontWeight: '600',
                    color: '#09090B',
                    cursor: 'pointer'
                  }}
                >
                  <span>{faq.q}</span>
                  {isOpen ? <ChevronUp size={18} color="#64748B" /> : <ChevronDown size={18} color="#64748B" />}
                </button>

                {isOpen && (
                  <div style={{ padding: '0 18px 16px 18px', fontSize: '13.5px', color: '#64748B', lineHeight: '1.6' }}>
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Getting Started CTA */}
      <div style={{
        backgroundColor: '#09090B',
        borderRadius: '20px',
        padding: '32px',
        color: '#FFFFFF',
        display: 'flex',
        alignItems: 'center',
        justify: 'space-between',
        flexWrap: 'wrap',
        gap: '20px'
      }}>
        <div>
          <h3 style={{ fontSize: '22px', fontWeight: '700', color: '#FFFFFF', marginBottom: '6px' }}>Ready to explore your knowledge base?</h3>
          <p style={{ fontSize: '13.5px', color: '#A1A1AA' }}>Upload your first document or start asking questions in the grounded chat.</p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <button
            onClick={() => setActiveTab('upload')}
            style={{
              backgroundColor: '#FFFFFF',
              color: '#09090B',
              border: 'none',
              padding: '10px 20px',
              borderRadius: '9999px',
              fontSize: '13.5px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            <UploadCloud size={16} />
            <span>Upload Document</span>
          </button>

          <button
            onClick={() => setActiveTab('chat')}
            style={{
              backgroundColor: 'transparent',
              color: '#FFFFFF',
              border: '1px solid #3F3F46',
              padding: '10px 20px',
              borderRadius: '9999px',
              fontSize: '13.5px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            <span>Start Chat</span>
            <ArrowRight size={16} />
          </button>
        </div>
      </div>

    </div>
  );
}
